server:
  port: 0

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false&serverTimezone=UTC
    username: root
    password: zyx20040720
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
